# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d17c70fe2750db35f2daf631b71056e53ad9d047af21d73288d161ff99f1640f040973258ac0547f760dbe7292f8de11009dc22caf72875a4bf5f241d71fab3

test:
  secret_key_base: 60f185b74779b507fddfe7b4afe7c73bca4e1f500c1e2f6303efa025fb504fe4bbd6b97a9d7dec2091963b3dc4529e018d1bc821ca1aec5733b55e6b75b98847

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
